schema = {
    "listen": [
        {"name": "artist_name", "type": "string"},
        {"name": "title", "type": "string"},
        {"name": "duration", "type": "double"},
        {"name": "auth", "type": "string"},
        {"name": "level", "type": "string"},
        {"name": "city", "type": "string"},
        {"name": "stateName", "type": "string"},
        {"name": "userAgent", "type": "string"},
        {"name": "gender", "type": "string"},
        {"name": "registration", "type": "long"},
        {"name": "key", "type": "float"},
        {"name": "key_confidence", "type": "double"},
        {"name": "loudness", "type": "double"},
        {"name": "song_hotttnesss", "type": "double"},
        {"name": "tempo", "type": "double"},
        {"name": "song_id", "type": "string"},
        {"name": "year", "type": "float"},
    ],
    "auth": [
        {"name": "level", "type": "string"},
        {"name": "city", "type": "string"},
        {"name": "stateName", "type": "string"},
        {"name": "userAgent", "type": "string"},
        {"name": "gender", "type": "string"},
        {"name": "registration", "type": "long"},
        {"name": "success", "type": "string"},
    ],
    "status_change": [
        {"name": "level", "type": "string"},
        {"name": "city", "type": "string"},
        {"name": "stateName", "type": "string"},
        {"name": "userAgent", "type": "string"},
        {"name": "gender", "type": "string"},
        {"name": "registration", "type": "long"},
        {"name": "page", "type": "string"},
        {"name": "method", "type": "string"},
        {"name": "status", "type": "float"},
        {"name": "auth", "type": "string"},
    ],
    "page_view": [
        {"name": "level", "type": "string"},
        {"name": "city", "type": "string"},
        {"name": "stateName", "type": "string"},
        {"name": "userAgent", "type": "string"},
        {"name": "gender", "type": "string"},
        {"name": "registration", "type": "long"},
    ],
}
