apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-pi-{{ ds }}-{{ task_instance.try_number }}"
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "airflow.kr.ncr.ntruss.com/spark-py:v2"
  imagePullPolicy: Always
  imagePullSecrets: ["my-registry-secret"]
  mainApplicationFile: local:///opt/spark/examples/spark/gold/main.py
  deps:
    jars: ["local:///opt/spark/examples/spark/gold/postgresql/postgresql-42.5.4.jar"]
  arguments: ["listen", {{var.value.get("bucket_name")}},  {{yesterday_ds}}, {{var.value.get("obj_public_key")}}, {{var.value.get("obj_secret_key")}}, {{var.value.get("endpoint_url")}},  {{var.value.get("db_host")}}, {{var.value.get("db_schema")}}, {{var.value.get("db_id")}}, {{var.value.get("db_password")}}]
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
