apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "silver-page-view-{{ ds }}-{{ task_instance.try_number }}"
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "airflow.kr.ncr.ntruss.com/spark-py:v3"
  imagePullPolicy: IfNotPresent
  imagePullSecrets: ["my-registry-secret"]
  mainApplicationFile: local:///opt/spark/examples/spark/silver/process_all_events.py
  arguments: ["page_view", {{var.value.get("bucket_name")}},  {{yesterday_ds}}]
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
